import React, {useEffect, useState} from 'react';
import axios from 'axios';
import Head from 'next/head';
import PieChart from '../components/dashboard/PieChart';
import BarChart from '../components/dashboard/BarChart';
import {months} from '../components/constant/monthConstant';

export default function Home() {
  const [currentMonthExpenses, setCurrentMonthExpenses] = useState({});

  useEffect(() => {
    const baseURL = '/api/expenses';
    axios.get(baseURL).then((response) => {
      if (response.data.status === 'OK') {
        const currentMonthExpenses = response.data.expenses.filter(
          (item) => item.month == new Date().getMonth() + 1
        );
        const categoryBasedExpense = {};
        currentMonthExpenses.forEach((item) => {
          if (!categoryBasedExpense[item.category]) {
            categoryBasedExpense[item.category] = [item];
          } else {
            categoryBasedExpense[item.category].push(item);
          }
        });
        setCurrentMonthExpenses(categoryBasedExpense);
      }
    });
  }, []);

  return (
    <>
      <Head>
        <title>Personal Money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-2xl font-bold">
          Summary of expenses in {months[new Date().getMonth() + 1]}
        </h1>
        <div className="flex flex-wrap justify-start items-start gap-5 mt-4 ">
          <PieChart currentMonthExpenses={currentMonthExpenses} />
          <BarChart currentMonthExpenses={currentMonthExpenses} />
        </div>
      </div>
    </>
  );
}
