import {useState} from 'react';
import Head from 'next/head';
import ExpensesTable from '../../components/expenses/ExpensesTable';
import ExpenseForm from '../../components/expenses/CreateForm';

export default function Expenses() {
  const [newModal, setNewModal] = useState(false);

  function toggleAddForm() {
    setNewModal(!newModal);
  }

  return (
    <>
      <Head>
        <title>Personal Money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-2">
        <div className="flex items-end">
          <div className="flex-1">
            <h1 className="font-bold text-2xl text-zinc-800 dark:text-slate-300">
              Expenses
            </h1>
            <p className="text-sm">These are your expenses of the month.</p>
          </div>
          <div>
            <span>New Expense</span>
            <button
              className="bg-teal-700 hover:bg-teal-600 rounded-md shadow h-9 w-9 duration-300 ml-2"
              onClick={() => setNewModal(!newModal)}
            >
              {newModal ? (
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 inline text-stone-50 duration-75 rotate-45"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 4v16m8-8H4"
                  />
                </svg>
              ) : (
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 inline text-stone-50"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 4v16m8-8H4"
                  />
                </svg>
              )}
            </button>
          </div>
        </div>
        {newModal && <ExpenseForm onAdd={toggleAddForm} />}
        {!newModal && <ExpensesTable />}
      </div>
    </>
  );
}
